version: "2.1"

services:
  appdb:
    image: postgres
    container_name: appdb
    ports:
      - "5432:5432"
    volumes:
      - appdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: extagramdb
    networks:
      - test

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/mybucket;
      /usr/bin/mc policy set public myminio/mybucket;
      exit 0;
      "

  keycloakdb:
    image: postgres
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    #command: start-dev
    ports:
      - "7000:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloakdb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json:ro
      - ./themes/:/opt/keycloak/themes/
    depends_on:
      - keycloakdb


#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - test
#    depends_on:
#      - db
#    volumes:
#      - gradle-cache:/home/gradle/.gradle

networks:
  test:
    driver: bridge

volumes:
  appdb:
  minio:
  keycloakdb: